### ISSUE TITLE
在最后manage.py runserver时报错

### ISSUE THREAD

**Issue by Noahyuweihua** [Pzqqt/Django_Transportation_Management_System#11]
D:\github\Django_Transportation_Management_System>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
  File "D:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\github\Django_Transportation_Management_System\wuliu\templatetags\wuliu_extras.py", line 6, in <module>
    from ..common import get_global_settings, is_logged_user_has_perm, get_logged_user, PERMISSION_TREE_LIST
ImportError: cannot import name 'PERMISSION_TREE_LIST' from partially initialized module 'wuliu.common' (most likely due to a circular import) (D:\github\Django_Transportation_Management_System\wuliu\common.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "D:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "D:\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "D:\Python39\lib\site-packages\django\core\management\base.py", line 475, in check
    all_issues = checks.run_checks(
  File "D:\Python39\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "D:\Python39\lib\site-packages\django\core\checks\templates.py", line 60, in check_for_template_tags_with_the_same_name
    for module_name, module_path in get_template_tag_modules():
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'wuliu.templatetags.wuliu_extras': cannot import name 'PERMISSION_TREE_LIST' from partially initialized module 'wuliu.common' (most likely due to a circular import) (D:\github\Django_Transportation_Management_System\wuliu\common.py)

请问这是什么原因呢

**Comment by Pzqqt** [comment]
你肯定是乱改代码了。如果不知道怎么解决，就自己把它恢复到改之前的状态。

另外，第一次runserver请务必严格按照 [readme.md的Usage部分](https://github.com/Pzqqt/Django_Transportation_Management_System#usage) 操作，如果在Windows系统下安装和使用git不够方便，可以用WSL2，或者虚拟机。
