### ISSUE TITLE
init_database.sh报错

### ISSUE THREAD

**Issue by avesed** [Pzqqt/Django_Transportation_Management_System#5]
抱歉我是个还在学习过程中的小白
环境为Ubuntu server 22.04.1 LTS, MySQL 5.7, Python 3.10, Django 4.1

直接运行init_database.sh错误提示：

error: patch failed: wuliu/common.py:46
error: wuliu/common.py: patch does not apply
error: patch failed: wuliu/urls.py:1
error: wuliu/urls.py: patch does not apply

手动更改文件后尝试运行runserver，错误提示为：

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 564, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 262, in connect
    conn_params = self.get_connection_params()
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/mysql/base.py", line 218, in get_connection_params
    if settings_dict["HOST"].startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'

看起来都是数据库错误，有没有可能直接手动导入数据库呢？
求大佬帮忙

**Comment by avesed** [comment]
刚刚尝试了一下手动导入json文件，但还是继续报错，大佬能不能加个qq：**********，帮个忙，谢谢啦

**Comment by Pzqqt** [comment]
> - 编辑PPWuliu/settings.py，手动配置以下这些项目：
>   - `SECRET_KEY`
>   - `DATABASES`

这一步做了吗？

**Comment by avesed** [comment]
已经配置过了

SECRET_KEY = os.getenv("Qwer!234")
PBKDF2_ITERATIONS = 3

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('wuliu'),
        'USER': os.getenv('wuliu'),
        'PASSWORD': os.getenv('passcode'),
        'HOST': os.getenv('127.0.0.1'),
        'PORT': os.getenv('53'),
    }
}

**Comment by Pzqqt** [comment]
> 已经配置过了
> 
> SECRET_KEY = os.getenv("Qwer!234") PBKDF2_ITERATIONS = 3
> 
> DATABASES = { 'default': { 'ENGINE': 'django.db.backends.mysql', 'NAME': os.getenv('wuliu'), 'USER': os.getenv('wuliu'), 'PASSWORD': os.getenv('passcode'), 'HOST': os.getenv('127.0.0.1'), 'PORT': os.getenv('53'), } }

你配置了个寂寞，自己百度一下`os.getenv`。

**Comment by avesed** [comment]
😅😅😅🥲🥲没仔细看文档， 谢谢大佬
